[package]
name = "md_net"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
name = "md_net"

[dependencies]
libc = "0.2.150"
md_parser = { path = "../md_parser", features = ["pap"] }
